name: Build iOS IPA

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14  # Versión específica

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.32.8"
        
    - name: Check environment
      run: |
        flutter doctor -v
        echo "Pubspec content:"
        cat pubspec.yaml | head -20
        
    - name: Install dependencies
      run: flutter pub get --verbose
      timeout-minutes: 10
      
    - name: Build iOS
      run: flutter build ios --release --no-codesign --verbose
      
    - name: Package IPA
      run: |
        mkdir -p Payload
        cp -r build/ios/iphoneos/Runner.app Payload/
        zip -r app.ipa Payload
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: app.ipa