name: Build iOS IPA

on:
  workflow_dispatch: # lo lanzas manualmente
  push:
    branches:
      - master # cámbialo si usas otra rama

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. Descargar repo
      - uses: actions/checkout@v3

      # 2. Instalar Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8" # cámbialo a tu versión
          channel: stable

      # 3. Instalar dependencias
      - name: Flutter pub get
        run: flutter pub get

      # 4. Compilar sin firmar
      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      # 5. Crear archivo .ipa
      - name: Package IPA
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r app.ipa Payload

      # 6. Guardar artefacto
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: app.ipa
