name: Build iOS IPA

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. Descargar repo
      - uses: actions/checkout@v3

      # 2. Instalar Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"
          channel: stable

      # 3. Verificar instalación de Flutter
      - name: Verify Flutter installation
        run: flutter doctor -v

      # 4. Instalar dependencias con manejo de errores
      - name: Flutter pub get
        run: |
          flutter clean
          flutter pub get --verbose
        timeout-minutes: 5

      # 5. Compilar sin firmar
      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign --verbose

      # 6. Crear archivo .ipa
      - name: Package IPA
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r app.ipa Payload

      # 7. Guardar artefacto
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: app.ipa